name: CI

on:
  push:
    branches:
      - main

env:
  MK_APPLICATION_NAME: ${{ github.event.repository.name }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-latest-large
          - macos-26
    steps:
      - uses: actions/checkout@v5

      - name: Collect system information
        id: system
        run: |
          echo "SYSTEM_ARCH=$(uname -m)" >> "$GITHUB_OUTPUT"
          echo "SYSTEM_TYPE=$(uname -s)" >> "$GITHUB_OUTPUT"

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build binary
        run: ./gradlew nativeCompile --no-daemon

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MK_APPLICATION_NAME }}-${{ steps.system.outputs.SYSTEM_TYPE }}-${{ steps.system.outputs.SYSTEM_ARCH }}
          path: build/native/nativeCompile/*

  container:
    runs-on: ${{ matrix.platform }}
    needs:
      - build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - name: Collect system information
        id: system
        run: |
          echo "SYSTEM_ARCH=$(uname -m)" >> "$GITHUB_OUTPUT"
          echo "SYSTEM_TYPE=$(uname -s)" >> "$GITHUB_OUTPUT"

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MK_APPLICATION_NAME }}-${{ steps.system.outputs.SYSTEM_TYPE }}-${{ steps.system.outputs.SYSTEM_ARCH }}
          path: build/native/nativeCompile

      - name: List artifacts
        run: ls -Al build/native/nativeCompile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},suffix=-${{ steps.system.outputs.SYSTEM_ARCH }}
            type=edge,suffix=-${{ steps.system.outputs.SYSTEM_ARCH }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.run_id }}
          matrix-key: ${{ steps.system.outputs.SYSTEM_ARCH }}
          outputs: |-
            digest: ${{ steps.build.outputs.digest }}

  manifest:
    runs-on: ubuntu-latest
    needs:
      - container
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: ${{ github.run_id }}

      - name: Transform output
        id: transform
        run: |
          PIPELINE='.digest | to_entries | map("${{ env.REGISTRY }}/${{ github.repository }}@" + .value) | .[]'
          INPUT='${{ fromJSON(steps.read.outputs.result) }}'
          RESULT=$(jq -r "${PIPELINE}" - <<< "${INPUT}")
          echo "sources=${RESULT}" >> "$GITHUB_OUTPUT"

      - uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          sources: |
            ${{ steps.transform.outputs.sources }}
